import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner'
import Footer from '../components/Footer'
import Header from '../components/Header'
import LargeCard from '../components/LargeCard'
import MediumCard from '../components/MediumCard'
import SmallCard from '../components/SmallCard'
import styles from '../styles/Home.module.css'

export default function Home({exploreData, cardsData}) {
  return (
    <div className="">
      <Head>
        <title>pocketclass</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pc_favicon.ico" />
      </Head>
      {/* header */}
      <Header />
      {/* banner */}
      <Banner />

      <main className='max-w-7xl mx-auto px-8 py-8 sm:px-16'>
        <section>
          <h2 className="text-4xl font-semibold py-5">Explore Classes Nearby</h2>
          {/* APIs */}
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-4">
          {exploreData?.map(({img, distance, location}) => (
            <SmallCard key={img}
                       img={img} 
                       distance={distance} 
                       location={location}/>
          ))}
          </div>
        </section>

        <section>
          <h2 className="text-4xl font-semibold py-8 pb-5">Learn Anything</h2>
          <div className='flex space-x-3 overflow-scroll scrollbar-hide p-3'>
          {cardsData?.map(({img, title}) => (
            <MediumCard key={img}
                        img={img}
                        title={title}/>
          ))}
          </div>
        </section>

        <section>
          <LargeCard 
          img='https://links.papareact.com/4cj'
          title='Become an Instructor'
          description='Teach your Passion'
          buttonText="I'm Interested"/>
        </section>
      </main>

      <Footer />
      
    </div>
  )
}

export async function getStaticProps() {
  // pulls json array of {"img","location","distance"}
  const exploreData = await fetch('https://links.papareact.com/pyp').
  then(res => res.json());

  const cardsData = await (await fetch('https://links.papareact.com/zp1').
  then(res => 
    res.json()
  ));

  return {
    props: {
      exploreData,
      cardsData
    }
  }
}